-- Criar database mindcard antes de iniciar
-- TABELAS FORTES PRIMÁRIAS
CREATE TABLE TBL_USUARIO(
  ID_USUARIO BIGINT PRIMARY KEY IDENTITY,
  TX_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  TX_SENHA VARCHAR(60) NOT NULL,
  TX_NOME VARCHAR(70) NOT NULL,
);
CREATE TABLE TBL_CONQUISTA(
    ID_CONQUISTA BIGINT PRIMARY KEY IDENTITY,
    TX_OBJETIVO VARCHAR(250) NOT NULL,
    NB_RECOMPENSA INT(3) NOT NULL,
    TX_NOME VARCHAR(40) NOT NULL
);
CREATE TABLE TBL_MISSAO(
    ID_MISSAO BIGINT PRIMARY KEY IDENTITY,
    DT_PRAZO DATETIME NOT NULL,
    NB_RECOMPENSA INT(3) NOT NULL,
    TX_OBJETIVO VARCHAR(40) NOT NULL,
    TX_NOME VARCHAR(50) NOT NULL
);
CREATE TABLE TBL_ESTILO_BARALHO(
    ID_ESTILO_BARALHO BIGINT PRIMARY KEY IDENTITY,
    NB_VALOR INT(3) NOT NULL,
    TX_NOME VARCHAR(20) NOT NULL
);
--TABELAS FRACAS EM RELAÇÃO A OUTRA TABELA
CREATE TABLE TBL_BARALHO(
    ID_BARALHO BIGINT PRIMARY KEY IDENTITY,
    TX_NOME VARCHAR(30) NOT NULL,
    ID_USUARIO BIGINT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO)
);
CREATE TABLE TBL_BARALHO_COMUNIDADE(
    ID_BARALHO_COMUNIDADE PRIMARY KEY IDENTITY,
    TX_NOME VARCHAR(30) NOT NULL,
    ID_AUTOR_USUARIO BIGINT NOT NULL,
    TX_TAGS VARCHAR(60) NOT NULL,
    FOREIGN KEY (ID_AUTOR_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO)
);
CREATE TABLE TBL_CARTA_TEXTO(
    ID_CARTA_TEXTO BIGINT PRIMARY KEY IDENTITY,
    TX_NOME VARCHAR(30) NOT NULL,
    TX_CONTEUDO VARCHAR(1000),
    ID_BARALHO BIGINT NOT NULL,
    FOREIGN KEY (ID_BARALHO) REFERENCES TBL_BARALHO (ID_BARALHO)
);
CREATE TABLE TBL_CARTA_PERGUNTA(
    ID_CARTA_PERGUNTA BIGINT PRIMARY KEY IDENTITY,
    TX_NOME VARCHAR(30) NOT NULL,
    TX_PERGUNTA VARCHAR(1000) NOT NULL,
    TX_RESPOSTA VARCHAR(1000) NOT NULL,
    ID_BARALHO BIGINT NOT NULL,
    FOREIGN KEY (ID_BARALHO) REFERENCES TBL_BARALHO (ID_BARALHO)
);
-- TABELAS DE RELACIONAMENTOS "MUITOS PRA MUITOS"
CREATE TABLE TBL_REL_USUARIO_ESTILO(
    ID_USUARIO BIGINT NOT NULL,
    ID_ESTILO_BARALHO BIGINT NOT NULL,
    FOREIGN KEY (ID_ESTILO_BARALHO) REFERENCES TBL_ESTILO_BARALHO (ID_ESTILO_BARALHO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO)
);
CREATE TABLE TBL_REL_USUARIO_MISSAO(
    ID_USUARIO BIGINT NOT NULL,
    ID_MISSAO BIGINT NOT NULL,
    FOREIGN KEY (ID_MISSAO) REFERENCES TBL_MISSAO (ID_MISSAO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO)
);
CREATE TABLE TBL_REL_USUARIO_CONQUISTA(
    ID_USUARIO BIGINT NOT NULL,
    ID_CONQUISTA BIGINT NOT NULL,
    FOREIGN KEY (ID_CONQUISTA) REFERENCES TBL_CONQUISTA (ID_CONQUISTA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO)
);
